#96 docs(contributor) : 커밋 컨벤션
StockfolioOfficial/back-landing-career pull request #101
Opened 2021-09-03 08:51 UTC by lunayyko

**Description**
필수 리뷰어:

---
# 진행 배경
## 작업 목표
- 브랜칭 규칙 및 커밋 컨벤션 마크다운 파일 추가
---

# 결과
## 변경 후
- 내용
---

# 어려웠던 점
- 내용
---

# 레퍼런스
- 내용, 실행 방법 및 확인 방버
---
# 기타
- 내용

2021-09-10 02:30 UTC, RebirthLee requested changes
![image](https://user-images.githubusercontent.com/17996172/132789668-4ecd3dfe-18da-4d9d-9eec-3d229b2c5bfd.png)
띄어쓰기 처리가 되었으면 좋겠습니다

2021-09-13 08:56 UTC, lunayyko commented
> ![image](https://user-images.githubusercontent.com/17996172/132789668-4ecd3dfe-18da-4d9d-9eec-3d229b2c5bfd.png)
> 띄어쓰기 처리가 되었으면 좋겠습니다

넵

2021-09-13 09:45 UTC, lunayyko commented
띄어쓰기 수정하고 업데이트 했습니다!

2021-09-14 03:24 UTC, damdream commented
LGTM~~~!

2021-09-14 05:45 UTC, damdream reviewed
LGTM!

2021-09-14 06:06 UTC, lunayyko reviewed
수정완료했습니다 ^_^

2021-09-14 06:25 UTC, damdream reviewed
수정사항 확인했습니다!

2021-09-14 06:25 UTC, damdream commented
> LGTM!

2021-09-14 06:26 UTC, damdream approved these changes

2021-09-17 03:39 UTC, RebirthLee approved these changes

2021-09-17 03:39 UTC, merged